# Generated by Django 3.0.3 on 2020-05-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=12)),
                ('mail', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
