# Generated by Django 3.0.3 on 2020-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac_', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='To_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=' '),
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(default='', upload_to='media/img/'),
        ),
    ]
